▲示例4.1：标量的示例

In [1]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5  # 1.2×10 的5次方120000

▲示例4.2：用 NumPy 的一维数组表示向量

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # 用一维数组表示向量
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


▲示例4.3：用 NumPy 的二维数组表示矩阵

In [6]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2×3矩阵
print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])  # 3×2矩阵
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


▲示例4.4：用 NumPy 的数组表示 3 阶张量

In [4]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
                      [2, 3, 4, 5],
                      [4, 5, 6, 7]],
              
                     [[1, 2, 3, 4],
                      [3, 4, 5, 6],
                      [5, 6, 7, 8]]])  # (2,3,4)的3阶张量
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


#### 问题
　请在 Jupyter Notebook 的单元格中用 NumPy 编写数组，分别表示标量、向量、矩阵和 3 阶张量。

#### 解答示例

▲示例4.5：解答示例

In [7]:
import numpy as np

# 标量
a = 1.5
print(a)

print()

# 向量
b = np.array([1, 2, 3, 4, 5])
print(b)

print()

# 矩阵
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)

print()

# 3阶张量
d = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              
              [[8, 7, 6],
               [5, 4, 3],
               [2, 1, 0]]])
print(d)

1.5

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[8 7 6]
  [5 4 3]
  [2 1 0]]]
