▲示例4.10：使用 NumPy 计算矩阵乘积

In [2]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[2, 1],
              [2, 1],
              [2, 1]]) 

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


▲示例4.11：使用 NumPy 计算各元素乘积

In [3]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]]) 

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


#### 问题
　请计算示例 4.12 中，矩阵 a 和矩阵 b 的矩阵乘积以及矩阵 c 和矩阵 d 的每个元素的乘积。

▲示例4.12：问题

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 矩阵乘积



c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 每个元素的乘积


####解答示例

▲示例4.13：解答示例

In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 矩阵乘积
print(np.dot(a, b))
      
print()

c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 每个元素的乘积
print(c*d)

[[ 5  8]
 [ 8 14]]

[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
