▲示例4.14：转置矩阵

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 矩阵

print(a.T)  # 转置

[[1 4]
 [2 5]
 [3 6]]


▲示例4.15：转置后进行矩阵乘积计算

In [2]:
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]])  # 2×3矩阵
b = np.array([[0, 1, 2],
             [1, 2, 3]])  #2×3矩阵,这种形态下无法计算矩阵乘积

# print(np.dot(a, b))  # 不转置而求矩阵乘积时会报错
print(np.dot(a, b.T))  # 转置后可以计算矩阵乘积

[[ 5  8]
 [ 8 14]]


#### 问题
　请在示例 4.16 的代码中将矩阵 a 或矩阵 b 转置，以计算矩阵 a 和矩阵 b 的矩阵乘积。

▲示例4.16：问题

In [3]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 矩阵乘积



#### 解答示例

▲示例4.17：解答示例

In [5]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 矩阵乘积
print(np.dot(a, b.T))

[[ 5 11]
 [ 8 20]]
