▲示例4.18：使用 eye() 函数生成单位矩阵

In [6]:
import numpy as np

print(np.eye(2))  # 2×2的单位矩阵
print()
print(np.eye(3))  # 3×3的单位矩阵
print()
print(np.eye(4))  # 4×4的单位矩阵

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


▲示例4.19：使用 linalg.det() 函数计算行列式

In [7]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.det(a))  # 行列式不为0的情况

b = np.array([[1, 2],
              [0, 0]])
print(np.linalg.det(b))  # 行列式为0的情况

-2.0000000000000004
0.0


▲示例4.20
：使用 linalg.inv() 函数得到逆矩阵

In [8]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.inv(a))  # 逆矩阵

b = np.array([[1, 2],
              [0, 0]])
# print(np.linalg.inv(b))  #  由于不存在逆矩阵，因此会出现错误

[[-2.   1. ]
 [ 1.5 -0.5]]


#### 问题
　在示例 4.21 中计算矩阵 a 的行列式，如果存在逆矩阵，则计算逆矩阵。

▲示例4.21：问题

In [9]:
import numpy as np

a = np.array([[1, 1],
              [1, 2]]) 

# 行列式


# 逆矩阵



#### 解答示例

▲示例4.22：解答示例

In [10]:
import numpy as np

a = np.array([[1, 1],
              [1, 2]]) 

# 行列式
print(np.linalg.det(a))

print()

# 逆矩阵
print(np.linalg.inv(a))

1.0

[[ 2. -1.]
 [-1.  1.]]
