Chapter1	NumPy的基础
----------------------------------------
1.1 NumPy 的基础与安装方法
----------------------------------------
1.1.4 NumPy入门教程
----------------------------------------

In [2]:
1 + 2

3

In [3]:
type((1, 2, 3))

tuple

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [9]:
a * 3

array([3, 6, 9])

In [10]:
a + 2

array([3, 4, 5])

In [6]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [7]:
b = np.array([2, 2, 0])

In [8]:
a + b

array([3, 4, 3])

In [11]:
a / b

/tmp/ipykernel_67355/1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([0.5, 1. , inf])

In [12]:
a * b

array([2, 4, 0])

In [13]:
np.dot(a, b)

6

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [9]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c.shape

(2, 3)

In [20]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

In [21]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [22]:
d.shape

(2, 4, 3)

In [23]:
np.sum(c)

21

In [24]:
np.sum(c, axis=1)

array([ 6, 15])

In [25]:
np.sum(c, axis=0)

array([5, 7, 9])

In [26]:
np.sum(d)

300

In [27]:
np.sum(d, axis=0)

array([[14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [28]:
np.sum(d, axis=1)

array([[22, 26, 30],
       [70, 74, 78]])

In [29]:
np.sum(d, axis=2)

array([[ 6, 15, 24, 33],
       [42, 51, 60, 69]])

In [30]:
c.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
np.random.randn()

-0.05033588214411729

In [37]:
np.random.rand()

0.09620453064128931

In [38]:
np.random.randn(2, 3)

array([[-0.13319456,  0.04122304, -2.47996823],
       [ 0.34726679,  0.43200486, -0.88727352]])

In [2]:
a

array([1, 2, 3])

In [3]:
a[0]

1

In [4]:
a[2]

3

In [5]:
a

array([1, 2, 3])

In [6]:
a[1] = 3

In [7]:
a

array([1, 3, 3])

In [10]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
c[0, 0]

1

In [12]:
[0, 2]

[0, 2]

In [13]:
c[1, 2]

6

In [14]:
d = np.array([0, 5, 2, 7, 1, 9])

In [15]:
d[1:5]

array([5, 2, 7, 1])

In [16]:
d[1:3]

array([5, 2])

In [17]:
d[0:5:2]

array([0, 2, 1])

In [18]:
d[::-1]

array([9, 1, 7, 2, 5, 0])

In [19]:
import time # 导入用于处理时间的模块
def calculate_time():
    a = np.random.randn(100000)
    b = list(a) # 转换为列表
    start_time = time.time() #  设置开始时间
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using NumPy\t %f sec" % (time.time()-start_time))
    start_time = time.time() # 再次设置开始时间
    for _ in range(1000):
       sum_2 = sum(b)
    print("Not using NumPy\t %f sec" % (time.time()-start_time))

In [20]:
calculate_time()

Using NumPy	 0.022759 sec
Not using NumPy	 2.791894 sec


In [21]:
a = np.random.randn(10000000)

In [22]:
%timeit np.sum(a)

4.01 ms ± 50.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%timeit sum(a)

440 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


1.2 多维数据结构ndarray的基础
----------------------------------------
1.2.2 属性（attributes）
----------------------------------------

In [34]:
import numpy as np # 导入NumPy模块

In [35]:
a = np.array([1, 2, 3]) #  生成ndarray实例

In [33]:
type(a) # 确认对象的类

numpy.ndarray

In [27]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
a

array([1, 2, 3])

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b.T #进行转置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
a.T # 因为a.ndim<2，所以没有变化

array([1, 2, 3])

In [37]:
a.data # 显示内存中的地址

In [38]:
a.dtype # 显示数据的类型

dtype('int64')

In [39]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [40]:
b.flags #  可以获取各种信息

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False