# Chapter2 NumPy与数组操作

## 2.1 数组形状变换函数

### 2.1.1 np.reshape

In [2]:
import numpy as np

In [3]:
a = np.arange(12)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b = np.reshape(a, (3, 4)) # 变形为3×4的二维数组

In [6]:
b # 确认变形是否成功

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
b[0, 1] = 0 # 更改其中一个元素的值

In [8]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a # a中相应元素的值也发生了变化

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
c = np.arange(12) # 再次创建相同的数组

In [11]:
d = np.reshape(c, (3,4), order='C') # 通过指定order参数，可以改变元素的排列顺序

In [12]:
d #  'C'为默认设置，因此输出的结果仍然是一样的

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
d = np.reshape(c, (3, 4), order='F') # 如果将order设置为'F'，则首先对高维度元素的索引进行变形

In [14]:
d

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [15]:
np.reshape(c, (3, 5)) #如果变形后的数组的shape与元素数量不匹配，就会导致运行时错误发生

ValueError: cannot reshape array of size 12 into shape (3,5)

In [16]:
a = np.arange(12) # 再次创建同一数组

In [17]:
np.reshape(a, (3, -1)) #  将shape指定为(n, –1)，就会得到n×m（m是对数组中元素数量进行适配得到的值）的数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.reshape(a, (-1, 6)) # 尝试设置不同的值

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
a = np.arange(12).reshape((3, 4))

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b = np.arange(12).reshape((3, -1)) # 也可以使用-1

In [22]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
c = np.arange(15).reshape((3, 4)) # 如果元素数量与输出的数组不同，就会导致运行时发生错误

ValueError: cannot reshape array of size 15 into shape (3,4)

### 2.1.2 np.resize

In [24]:
a = np.arange(12)

In [25]:
np.reshape(a, (3, 4)) # 首先创建一个3×4的二维数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.resize(a, (3, 5)) #  当数组的尺寸大于元素数量时，原有的元素会被重复使用

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [27]:
np.resize(a, (3, 2)) # 当数组的尺寸小于元素数量时，原有的元素不会全部被使用

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
b = np.resize(a, (3, 4))

In [29]:
b[0, 1] = 0 # 修改数组中的元素

In [30]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a # 原有数组中的元素并没有同时被修改

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 2.1.3 ndarray.resize

In [32]:
a = np.arange(12) #  创建一个变形前的数组

In [33]:
a.resize((3, 4)) # 变形

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a.resize((3, 5)) #  和之前的np.resize函数调用不同，变形后的数组的shape与元素数量不匹配，因此会导致运行时错误发生

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [36]:
a.resize((3, 5), refcheck=False) #  将参数refcheck指定为False，程序会自动匹配数组的形状并填充相应的元素值。但是，对
# 于欠缺的元素使用0值进行填充

In [37]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  0,  0]])

In [38]:
b = np.arange(12) #  再次创建一个新的数组

In [39]:
c = b #  将b代入c中

In [40]:
c.resize((3, 4)) #只对c进行变形

In [41]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b #  对数组c所做的改动也会被反映到数组b中

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2.2 添加元素到数组末尾的函数

### 2.2.1 Python列表的append方法

In [43]:
a = [1, 2, 3]

In [44]:
a.append(2)

In [45]:
a

[1, 2, 3, 2]

In [46]:
b = np.arange(12).reshape((3, 4))

In [47]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
np.append(b, [1, 2, 3, 4]) # 如果不指定axis，返回的就是一维数组

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [49]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
np.append(b, [[12, 13, 14, 15]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.append(b, [12, 13, 14, 15], axis=0) # shape不一致时，会导致运行时产生错误

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
c = np.arange(12).reshape((3, 4))

In [53]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
d = np.linspace(0, 26, 12).reshape(3, 4) # 这次创建和c一样shape的数组

In [55]:
d

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [56]:
np.append(c,d, axis=0) #  指定axis为0时，将在行方向上对元素进行添加

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [57]:
np.append(c, d, axis=1) #  指定axis为1时，将在列方向上对元素进行添加

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
         2.36363636,  4.72727273,  7.09090909],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
        11.81818182, 14.18181818, 16.54545455],
       [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
        21.27272727, 23.63636364, 26.        ]])

#### 编写同样的代码，对ndarray与Python的列表的性能进行比较。

In [58]:
def np_append():
    a = np.array([1, 2, 3])
    for i in range(10000):
        a = np.append(a, [i])
    return a

In [59]:
def list_append():
    a = [1, 2, 3]
    for i in range(10000):
        a.append(i)
    return np.array(a)

In [60]:
%timeit np_append()

24.1 ms ± 476 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [61]:
%timeit list_append()

508 μs ± 6.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## 2.3 数组的真假值判断函数

### 2.3.1 np.all

In [62]:
import numpy as np

In [110]:
a = np.array([
[1, 1, 1],
[1, 0, 0],
[1, 0, 1],
])

In [111]:
np.all(a) #  a的元素为1时返回True，为0时返回False

False

In [112]:
b = np.ones((3, 3))

In [113]:
np.all(b)

True

In [114]:
np.all(a<2) #  a的元素全部都小于2时返回True

True

In [115]:
np.all(b%3<2) # 除以3之后的余数小于2

True

In [116]:
np.all(a, axis=0) 

array([ True, False, False])

In [117]:
np.all(a, axis=1)

array([ True, False, False])

In [118]:
a[2,0] = 0

In [119]:
a

array([[1, 1, 1],
       [1, 0, 0],
       [0, 0, 1]])

In [120]:
np.all(a, axis=0)

array([False, False, False])

In [121]:
np.all(a, axis=0, keepdims=True) #  指定keepdims=True

array([[False, False, False]])

In [122]:
a.all()

False

In [123]:
b.all()

True

In [124]:
a.all(axis=1)

array([ True, False, False])

In [125]:
(a<2).all()

True

In [126]:
a.all(keepdims=True)

array([[False]])

### 2.3.2 np.any

In [127]:
a = np.random.randint(10, size=(2, 3))

In [128]:
a

array([[6, 1, 3],
       [8, 3, 9]])

In [129]:
np.any(a==9) # 查找a的元素中是否包含元素9。

True

In [130]:
np.any(a==5)

False

In [131]:
np.any(a%2==0, axis=0)

array([ True, False, False])

In [132]:
np.any(a%2==1, axis=1)

array([ True,  True])

In [133]:
np.any(a%2==1, axis=1, keepdims=True) # 指定keepdims=True，对维度进行保留

array([[ True],
       [ True]])

In [134]:
np.any(a>2, keepdims=True)

array([[ True]])

In [135]:
(a%5==0).any()

False

In [136]:
(a>3).any()

True

In [137]:
b = np.random.randint(10, size=(2, 3))

In [138]:
b

array([[7, 3, 6],
       [4, 7, 7]])

In [139]:
(a==b).any(axis=1)

array([False, False])

In [140]:
(a==b).any(axis=1, keepdims=True)

array([[False],
       [False]])

## 2.4 指定条件获取元素索引的函数

### 2.4.1 np.where

In [142]:
import numpy as np

In [143]:
a = np.array([10, 12, 9, 3, 19])

In [144]:
a[a<10]

array([9, 3])

In [145]:
a = np.arange(20, 0, -2) # 首先创建一维数组

In [146]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [147]:
np.where(a < 10) #  获取小于10的索引

(array([6, 7, 8, 9]),)

In [148]:
a[np.where(a < 10)]

array([8, 6, 4, 2])

In [149]:
a = np.arange(12).reshape((3, 4))  # 指定为3×4的二维数组

In [150]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
np.where(a%2==0) #  只取出偶数元素

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))

In [155]:
np.where(a%2==0, 'even', 'odd') #  偶数返回even，奇数返回odd

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [156]:
np.where(a%2==0, 'even') # 如果只设置True，就会导致运行时产生错误

ValueError: either both or neither of x and y should be given

In [157]:
np.where(a%2==0, 'even', 'odd') # 偶数返回even，奇数返回odd

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [158]:
b = np.reshape(a, (3, 4))

In [159]:
c = b ** 2

In [160]:
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [161]:
np.where(b%2==0, b, c) # 只有奇数元素被转换成了c中的元素

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

In [162]:
np.where(b%2==0, b, (10, 8, 6, 4)) #  运用广播机制，使用(10, 8, 6, 4)重复的值

array([[ 0,  8,  2,  4],
       [ 4,  8,  6,  4],
       [ 8,  8, 10,  4]])

## 2.5 最大值、最小值的筛选函数

### 2.5.1 np.amax

In [163]:
import numpy as np

In [164]:
np.amax(np.array([1, 2, 3, 2, 1]))

3

In [165]:
arr = np.array([1, 2, 3, 4]).reshape((2, 2,))

In [166]:
arr

array([[1, 2],
       [3, 4]])

In [167]:
np.amax(arr, axis=0)

array([3, 4])

In [168]:
np.amax(arr, axis=1)

array([2, 4])

In [169]:
np.amax(arr, keepdims=True)

array([[4]])

In [170]:
### 2.5.2 ndarray.max

In [171]:
a = np.random.rand(20) # 使用rand创建20个随机数

In [172]:
a

array([0.98103776, 0.93524029, 0.09130248, 0.34094815, 0.01507814,
       0.008237  , 0.92880136, 0.7298601 , 0.10100478, 0.05104064,
       0.84157182, 0.37866831, 0.41710964, 0.99392401, 0.38757351,
       0.74592627, 0.23679561, 0.57256819, 0.08090372, 0.68985599])

In [173]:
a.max()

0.9939240086325646

In [174]:
a = a.reshape((4, 5))

In [175]:
a

array([[0.98103776, 0.93524029, 0.09130248, 0.34094815, 0.01507814],
       [0.008237  , 0.92880136, 0.7298601 , 0.10100478, 0.05104064],
       [0.84157182, 0.37866831, 0.41710964, 0.99392401, 0.38757351],
       [0.74592627, 0.23679561, 0.57256819, 0.08090372, 0.68985599]])

In [176]:
a.max()

0.9939240086325646

In [177]:
a.max(axis=0)

array([0.98103776, 0.93524029, 0.7298601 , 0.99392401, 0.68985599])

In [178]:
a.max(axis=1)

array([0.98103776, 0.92880136, 0.99392401, 0.74592627])

In [179]:
b = np.random.rand(30).reshape((2, 3, 5)) #  之后再使用三维数组进行尝试

In [180]:
b

array([[[0.92945801, 0.38111826, 0.57325949, 0.33951573, 0.48177898],
        [0.88354298, 0.39548889, 0.29273283, 0.44534755, 0.97118432],
        [0.35672706, 0.99466342, 0.647074  , 0.85005073, 0.2460386 ]],

       [[0.85139175, 0.1415677 , 0.06740551, 0.9535804 , 0.3204813 ],
        [0.30331781, 0.18950999, 0.74745423, 0.08023519, 0.06604026],
        [0.46897724, 0.72563205, 0.4780943 , 0.85803049, 0.50285815]]])

In [181]:
b.max(axis=0)

array([[0.92945801, 0.38111826, 0.57325949, 0.9535804 , 0.48177898],
       [0.88354298, 0.39548889, 0.74745423, 0.44534755, 0.97118432],
       [0.46897724, 0.99466342, 0.647074  , 0.85803049, 0.50285815]])

In [182]:
b.max(axis=1)

array([[0.92945801, 0.99466342, 0.647074  , 0.85005073, 0.97118432],
       [0.85139175, 0.72563205, 0.74745423, 0.9535804 , 0.50285815]])

In [183]:
b.max(axis=2)

array([[0.92945801, 0.97118432, 0.99466342],
       [0.9535804 , 0.74745423, 0.85803049]])

In [185]:
b = np.arange(10, dtype=np.float64)

In [186]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [187]:
b[3] = np.NaN # 将NaN代入

In [188]:
b.max()

nan

In [189]:
np.nanmax(b) # 使用nanmax，就会返回除NaN之外的元素中的最大值

9.0

### 2.5.3 np.amin

In [190]:
a = np.array([
[1.2, 1.3, 0.1, 1.5],
[2.1, 0.2, 0.3, 2.0],
[0.1, 0.5, 0.5, 2.3]])

In [191]:
np.amin(a) # 不对参数进行特别指定时

0.1

In [192]:
np.amin(a, axis=0) # 在行方向上逐个对最小值进行提取

array([0.1, 0.2, 0.1, 1.5])

In [193]:
np.amin(a, axis=1) #在列方向上逐个对最小值进行提取

array([0.1, 0.2, 0.1])

In [194]:
np.amin(a, axis=0, keepdims=True) #  返回的不是一维数组，而是二维数组

array([[0.1, 0.2, 0.1, 1.5]])

In [195]:
np.amin(a, axis=1, keepdims=True)

array([[0.1],
       [0.2],
       [0.1]])

In [196]:
a - np.amin(a, axis=1, keepdims=True) # 指定keepdims=True，就可以使用广播机制

array([[1.1, 1.2, 0. , 1.4],
       [1.9, 0. , 0.1, 1.8],
       [0. , 0.4, 0.4, 2.2]])

In [197]:
a - np.amin(a, axis=1) # 如果不指定keepdims=True，就无法顺利地进行计算

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

### 2.5.4 np.ndarray.min

In [198]:
a = np.array([
[1.2, 1.3, 0.1, 1.5],
[2.1, 0.2, 0.3, 2.0],
[0.1, 0.5, 0.5, 2.3]])

In [199]:
a.min() #  首先在不对参数进行指定的情况下提取最小值

0.1

In [200]:
a.min(axis=0) #  指定坐标轴提取最小值

array([0.1, 0.2, 0.1, 1.5])

In [201]:
a.min(axis=1)

array([0.1, 0.2, 0.1])

In [202]:
a.min(axis=0, keepdims=True)

array([[0.1, 0.2, 0.1, 1.5]])

In [203]:
a.min(axis=1, keepdims=True)

array([[0.1],
       [0.2],
       [0.1]])

## 2.6 返回数组中最大元素索引的函数

### 2.6.2 np.argmax


In [204]:
import numpy as np

In [205]:
a = np.random.randint(10, size=10) #首先生成一个一维数组

In [206]:
a # 对a中的数值进行确认

array([6, 0, 4, 1, 9, 7, 8, 2, 7, 6])

In [207]:
np.argmax(a)

4

In [208]:
a.argmax()

4

In [209]:
b = np.random.randint(10, size=(3, 4)) # 接下来生成一个3×4的二维数组

In [210]:
b # 对b中的元素进行确认

array([[0, 0, 8, 8],
       [5, 6, 0, 9],
       [9, 4, 6, 2]])

In [211]:
np.argmax(b) #  虽然需要获取的是二维数组中最大值的索引，但是返回的是降维成一维数组后的索引。因此这里获取的是1

7

In [212]:
b.argmax() # np.ndarray.argmax的用法也是相同的

7

In [213]:
b

array([[0, 0, 8, 8],
       [5, 6, 0, 9],
       [9, 4, 6, 2]])

In [214]:
np.argmax(b, axis=0) # 指定axis=0(在这种情况下为行)方向上的最大值（因为是从纵向查找最大值的索引，所以元素数量为4个）

array([2, 1, 0, 1])

In [215]:
b.argmax(axis=0) #  np.ndarray.argmax的用法也是相同的

array([2, 1, 0, 1])

In [216]:
np.argmax(b, axis=1) # 尝试将axis指定为1。这时需要查找列方向上的最大值(横向上元素中的最大值)

array([2, 3, 0])

In [217]:
b.argmax(axis=1)

array([2, 3, 0])

In [218]:
c = np.random.randint(10, size=(2, 3, 4)) #生成一个2×3×4的三维数组

In [219]:
c #  对c中的数值进行确认

array([[[7, 4, 9, 9],
        [4, 0, 9, 2],
        [3, 8, 2, 2]],

       [[1, 1, 3, 6],
        [4, 4, 9, 4],
        [2, 4, 2, 4]]])

In [220]:
np.argmax(c, axis=0)

array([[0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 1]])

In [221]:
c.argmax(axis=0)

array([[0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 1]])

In [222]:
np.argmax(c, axis=1)

array([[0, 2, 0, 0],
       [1, 1, 1, 0]])

In [223]:
c.argmax(axis=1)

array([[0, 2, 0, 0],
       [1, 1, 1, 0]])

In [224]:
np.argmax(c, axis=2)

array([[2, 2, 1],
       [3, 2, 1]])

In [225]:
c.argmax(axis=2)

array([[2, 2, 1],
       [3, 2, 1]])

### 2.6.4 np.argmin

In [226]:
d = np.array([
[1.2, 1.5, 2.3, 1.8],
[0.2, 2.5, 2.1, 2.0],
[3.1, 3.3, 1.5, 2.1]])

In [227]:
d.argmin() # 首先在不指定参数的情况下执行代码

4

In [228]:
np.argmin(d) # 同样地执行代码

4

In [229]:
np.unravel_index(np.argmin(d), d.shape) # 这样调用，返回的就是没有被降为一维数组的索引

(1, 0)

In [230]:
np.argmin(d, axis=0) # 接着对坐标轴进行指定

array([1, 0, 2, 0])

In [231]:
np.argmin(d, axis=1)

array([0, 0, 2])

In [232]:
d.argmin(axis=1) # ndarray.argmin也可以完成同样的处理

array([0, 0, 2])