# Chapter1	NumPy的基础
## 1.1 NumPy 的基础与安装方法

### 1.1.2　Python 的安装

```bash
［终端窗口］
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

［终端窗口］
$ brew install python3

［终端窗口］
$ python
```

#### 简单的辅导

In [1]:
1 + 2

3

In [2]:
1 - 2

-1

In [3]:
3 * 4

12

In [4]:
5 / 2

2.5

In [5]:
x = 5

In [6]:
x + 2

7

In [7]:
3 * x

15

In [8]:
print(x)

5


In [9]:
type((1, 2, 3)) # 使用type函数对数据类型进行确认

tuple

In [10]:
type([1, 2, 3])

list

In [11]:
(1, 2, 3, 4, 5)

(1, 2, 3, 4, 5)

In [12]:
a = (1, 2, 3, 4, 5) # 将元组代入变量a中

In [13]:
a[0]

1

In [14]:
b = [1, 2, 3, 4, 5] # 创建列表

In [15]:
b[1]

2

In [16]:
b[4]

5

In [17]:
dic = {'a': 1, 'b': 2, 'c': 3} # 创建字典

In [18]:
dic['a'] #使用冒号（ ：）左侧称为键（Key）的值引用保存的数据

1

In [19]:
for i in range(3):
    print(i)

0
1
2


In [20]:
def function(x):
    return x + 5

In [21]:
function(3)

8

#### IPython的安装

```bash
［终端窗口］
$ pip install ipython

［终端窗口］
$ ipython
```

### 1.1.3　NumPy的安装方法

```bash
［终端窗口］
$ pip install numpy

［终端窗口］
$ pip install numpy==1.14.3

［终端窗口］
$ sudo easy_install pip
```

#### 不使用pip的安装方法

```bash
［终端窗口］
$ sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose

［终端窗口］
$ brew tap homebrew/science && brew install python numpy scipy matplotlib
```

### 1.1.4 NumPy入门教程

```bash
［终端窗口］
$ ipython
```

In [22]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [23]:
a * 3

array([3, 6, 9])

In [24]:
a + 2

array([3, 4, 5])

In [25]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [26]:
b = np.array([2, 2, 0])

In [27]:
a + b

array([3, 4, 3])

In [28]:
a / b

/tmp/ipykernel_32889/1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([0.5, 1. , inf])

In [29]:
a * b

array([2, 4, 0])

In [30]:
np.dot(a, b)

6

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0, 10, 2) # (起点，终点，间隔)

array([0, 2, 4, 6, 8])

In [33]:
np.linspace(0, 10, 15) # 0~10划分为15等分

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [34]:
c = np.array([[1, 2, 3], [4, 5, 6]]) # 创建二维数组

In [35]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
c.shape

(2, 3)

In [37]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])  # 还可以创建三维数组

In [38]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [39]:
d.shape

(2, 4, 3)

In [40]:
np.sum(c)

21

In [41]:
np.sum(c, axis=1)

array([ 6, 15])

In [42]:
np.sum(c, axis=0)

array([5, 7, 9])

In [43]:
np.sum(d)

300

In [44]:
np.sum(d, axis=0)

array([[14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [45]:
np.sum(d, axis=1)

array([[22, 26, 30],
       [70, 74, 78]])

In [46]:
np.sum(d, axis=2)

array([[ 6, 15, 24, 33],
       [42, 51, 60, 69]])

In [47]:
c.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
np.random.randn()

-0.34713658732657793

In [52]:
np.random.rand()

0.022461883044454956

In [53]:
np.random.randn(2, 3)

array([[ 1.6593188 , -0.96113349,  1.58106326],
       [ 1.74995921,  0.66026972, -0.64420072]])

In [54]:
a

array([1, 2, 3])

In [55]:
a[0]

1

In [56]:
a[2]

3

In [57]:
a

array([1, 2, 3])

In [58]:
a[1] = 3

In [59]:
a

array([1, 3, 3])

In [60]:
a[1] = 2

In [61]:
a

array([1, 2, 3])

In [62]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
c[0, 0]

1

In [64]:
[0, 2]

[0, 2]

In [65]:
c[1, 2]

6

In [66]:
d = np.array([0, 5, 2, 7, 1, 9])

In [67]:
d[1:5]

array([5, 2, 7, 1])

In [68]:
d[1:3]

array([5, 2])

In [69]:
d[0:5:2]

array([0, 2, 1])

In [70]:
d[::-1]

array([9, 1, 7, 2, 5, 0])

In [71]:
a

array([1, 2, 3])

In [72]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a + c

array([[2, 4, 6],
       [5, 7, 9]])

In [74]:
a * c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [75]:
import time # 导入用于处理时间的模块
def calculate_time():
    a = np.random.randn(100000)
    b = list(a) # 转换为列表
    start_time = time.time() #  设置开始时间
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using NumPy\t %f sec" % (time.time()-start_time))
    start_time = time.time() # 再次设置开始时间
    for _ in range(1000):
       sum_2 = sum(b)
    print("Not using NumPy\t %f sec" % (time.time()-start_time))

In [76]:
calculate_time()

Using NumPy	 0.023619 sec
Not using NumPy	 2.742273 sec


In [77]:
a = np.random.randn(10000000)

In [78]:
%timeit np.sum(a)

4.03 ms ± 13.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [79]:
%timeit sum(a)

456 ms ± 15.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 1.2 多维数据结构ndarray的基础

### 1.2.2 属性（attributes）

In [80]:
import numpy as np # 导入NumPy模块

In [81]:
a = np.array([1, 2, 3]) #  生成ndarray实例

In [82]:
type(a) # 确认对象的类

numpy.ndarray

In [83]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [84]:
a

array([1, 2, 3])

In [85]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
b.T #进行转置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
a.T # 因为a.ndim<2，所以没有变化

array([1, 2, 3])

In [88]:
a.data # 显示内存中的地址

In [89]:
a.dtype # 显示数据的类型

dtype('int64')

In [90]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [91]:
b.flags #  可以获取各种信息

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [92]:
a.flat[1] # 显示将a转换为一维数组后其中的索引1的元素

2

In [93]:
b.flat[4]

5

In [94]:
c = np.array([1.-2.6j,2.1+3.j, 4.-3.2j]) # 创建以复数为元素的ndarray实例

In [95]:
c.real # 显示实数部分

array([1. , 2.1, 4. ])

In [96]:
c.imag # 显示虚数部分

array([-2.6,  3. , -3.2])

In [97]:
a.size #元素的数量

3

In [98]:
b.size

6

In [99]:
a.itemsize # 按字节序显示每个元素的字长

8

In [100]:
b.itemsize # 在某些环境中可能是4

8

In [101]:
c.size, c.itemsize

(3, 16)

In [102]:
a.nbytes # 按字节序显示数组的长度，在某些环境中可能是12

24

In [103]:
b.nbytes #  在某些环境中可能是24

48

In [104]:
c.nbytes

48

In [105]:
a.size * a.itemsize == a.nbytes #  这个等式成立

True

In [106]:
a.ndim # 显示维数

1

In [107]:
b.ndim

2

In [108]:
a.shape # 显示形状

(3,)

In [109]:
b.shape # 显示形状

(2, 3)

In [110]:
d = np.array([[[2,3,2],[2,2,2]],[[4,3,2],[5,7,1]]]) # 生成三维数组

In [111]:
d.shape, d.ndim # 显示形状和维数

((2, 2, 3), 3)

In [112]:
a.strides  #在各个维度方向上(axis=ndim,axis=ndim-1,…
# axis=1,axis=0)移动到下一个元素所需移动的字节数。在某些环境下可能为(4,)

(8,)

In [113]:
b.strides #  .ndim=2，在某些环境下可能为(12, 4)

(24, 8)

In [114]:
c.strides # .ndim = 3

(16,)

In [115]:
d.strides # .ndim=3在某些环境下可能为(24,12,4)

(48, 24, 8)

In [116]:
a.ctypes.data #  使用ctypes模块的操作

760242912

In [117]:
a.base # a的基类数组在什么地方

In [118]:
e = a[:2]

In [119]:
e.base

array([1, 2, 3])

In [120]:
e.base is a

True

In [121]:
a.base is e.base

False

1.2.4步长
----------------------------------------

In [124]:
a = np.random.randn(100,100)

In [125]:
b = np.array(a, order='C') # 行主序

In [127]:
c = np.array(a, order='F') # column-major

In [128]:
b.strides, c.strides #从步长上看，二者是相反的

((800, 8), (8, 800))

In [129]:
np.allclose(b, c)      # 确认数组的元素是否完全相同

True

In [131]:
x = np.ones((100000,)) # 将所有的元素都初始化为1

In [132]:
x

array([1., 1., 1., ..., 1., 1., 1.])

In [133]:
y = np.ones((100000*100,))[::100] # 每隔100个元素进行读取

In [134]:
x.strides # 为了移动到相邻的下一个元素，需要跳转8个字节的距离

(8,)

In [135]:
y.strides #为了移动到相邻的下一个元素，需要跳转800个字节的距离

(800,)

In [137]:
x.shape, y.shape

((100000,), (100000,))

In [138]:
%timeit x.sum() # 很明显这个速度更快

19.9 μs ± 213 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [139]:
%timeit y.sum()

489 μs ± 9.35 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [140]:
y_copy = np.copy(np.ones((100000*100,))[::100])

In [141]:
y_copy.strides

(8,)

In [142]:
%timeit y_copy.sum()

20.3 μs ± 198 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### 1.2.5 广播

In [144]:
a = np.array([1, 2, 3])

In [145]:
b = np.array([[1, 1, 1],[2, 4, 1]]) # 二维数组

In [146]:
b + a #  使用广播功能

array([[2, 3, 4],
       [3, 6, 4]])

## 1.3 广播

### 1.3.1 何谓广播

In [147]:
import numpy as np

In [148]:
np.array([[1, 2, 3]]) + [1]

array([[2, 3, 4]])

### 1.3.2 广播的运行机制

In [149]:
a = np.array([[1, 2]])

In [150]:
a.shape

(1, 2)

In [151]:
b = np.array([3, 4])

In [152]:
b.shape

(2,)

In [154]:
a + b

array([[4, 6]])

In [155]:
a = np.array([1, 2])

In [156]:
b = np.array([[3, 4],[2, 3]])

In [157]:
a

array([1, 2])

In [158]:
b

array([[3, 4],
       [2, 3]])

In [159]:
a.shape

(2,)

In [160]:
b.shape

(2, 2)

In [161]:
a + b

array([[4, 6],
       [3, 5]])

In [162]:
a = np.array([[2], [1]])

In [163]:
b = np.array([5])

In [164]:
c = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

In [165]:
a

array([[2],
       [1]])

In [166]:
b

array([5])

In [167]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [168]:
a.shape

(2, 1)

In [169]:
b.shape

(1,)

In [170]:
c.shape

(2, 2, 3)

In [171]:
a + b + c

array([[[ 8,  9, 10],
        [10, 11, 12]],

       [[14, 15, 16],
        [16, 17, 18]]])

## 1.4 切片

In [173]:
a = [1, 2, 3, 4, 5]

In [174]:
a[1:-1]

[2, 3, 4]

### 1.4.2 　切片的使用方法

In [175]:
import numpy as np

In [176]:
a = np.arange(15)

In [177]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [178]:
a[5:11:2]

array([5, 7, 9])

In [179]:
a = np.arange(10) #  创建包含10个连号数据的数组

In [180]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
a[1:5] # 1～4

array([1, 2, 3, 4])

In [182]:
a[2:8:2] #  2~7每隔一个

array([2, 4, 6])

In [183]:
a[::-1] # 逆序排列

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [184]:
a[:3] # 0～2

array([0, 1, 2])

In [185]:
a[4:] # 4～9

array([4, 5, 6, 7, 8, 9])

In [186]:
a[:3],a[3:] # 将3作为边界划分为两个数组

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [187]:
a[::2] # 指定间隔一个元素

array([0, 2, 4, 6, 8])

In [188]:
a[:] # 指定全范围内的数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.4.3 向高维数据结构扩展

In [189]:
b = np.arange(20).reshape(4,5) # 4×5的二维数组

In [190]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [191]:
b[1:3, 2:4] # 将第1~2行，第2~3列提取出来

array([[ 7,  8],
       [12, 13]])

In [192]:
b[:2, 1:] #  将第0~1行，第1~4列提取出来

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [193]:
b[::2, :] # 在行方向上每隔一个提取元素

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [194]:
b[:, ::2] # 在列方向上每隔一个提取元素

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [195]:
b[:, ::-1] # 逆順

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [196]:
b[::-1, ::-1] # 全部颠倒过来

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [197]:
c = np.zeros((3, 4, 5)) #  3×4×5的三维数组

In [198]:
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [199]:
c[1:, 1:4, :] = 1

In [200]:
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [201]:
c = np.zeros((3, 4, 5)) # 重置

In [202]:
c[:, 1:2, 3:] = 1

In [203]:
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [204]:
c = np.zeros((3, 4, 5)) # 重置

In [207]:
c[:, :, ::2] = 1 #  每两个一次

In [208]:
c

array([[[1., 0., 1., 0., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]],

       [[1., 0., 1., 0., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]],

       [[1., 0., 1., 0., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]]])

In [209]:
c = np.zeros((3, 4, 5)) #  重置

In [210]:
c[::2, ::2, ::2] = 1

In [211]:
c

array([[[1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.]]])

## 1.5 关于坐标轴和维度

### 1.5.1 ndarray的维度

In [212]:
import numpy as np

In [213]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [214]:
a.shape

(2, 3)

In [215]:
a.ndim

2

### 1.5.2 关于坐标轴

In [216]:
a = np.arange(6).reshape((3, 2))

In [217]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [218]:
a.shape

(3, 2)

In [219]:
b = np.array([a, a])

In [220]:
b.shape

(2, 3, 2)

In [221]:
b

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

### 1.5.3 　作为函数参数的axis

In [223]:
b.sum(axis=0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [224]:
b.sum(axis=0).shape

(3, 2)

In [225]:
b.sum(axis=1)

array([[6, 9],
       [6, 9]])

In [226]:
b.sum(axis=2)

array([[1, 5, 9],
       [1, 5, 9]])

In [227]:
b.sum(axis=2).shape

(2, 3)

## 1.6 ndarray的shape属性

### 1.6.1 ndarray.shape

In [228]:
import numpy as np

In [229]:
a = np.array([5, 3, 8, 9])

In [230]:
a

array([5, 3, 8, 9])

In [231]:
a.shape

(4,)

In [232]:
b = a.reshape((2, 2))

In [233]:
b

array([[5, 3],
       [8, 9]])

In [234]:
b.shape

(2, 2)

In [235]:
a

array([5, 3, 8, 9])

In [236]:
a.shape

(4,)

In [237]:
a.shape = (4, 1)

In [238]:
a

array([[5],
       [3],
       [8],
       [9]])

In [239]:
c = np.arange(12).reshape((3, 4))

In [240]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [241]:
c.shape

(3, 4)

In [242]:
c.shape=(1, 12)

In [243]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [244]:
c.shape = (13,) # 如果元素数量不正确，则会返回错误

ValueError: cannot reshape array of size 12 into shape (13,)

In [245]:
c.shape = (12,)

In [246]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [247]:
a = np.array([1, 2, 3, 4, 5]) #  简单的一维数组

In [248]:
a.shape

(5,)

In [249]:
b = np.array([[1], [2], [3], [4], [5]]) # 如果转换为纵向量其shape就变为(R,1)

In [250]:
b.shape

(5, 1)

## 1.7 元素数据类型的种类与指定方法

### 1.7.2 　数据类型

In [251]:
import numpy as np

In [252]:
a = np.array([0, 1, 2]) # 首先在什么都不指定的情况下生成数组

In [253]:
a.dtype #首先在什么都不指定的情况下生成数组

dtype('int64')

In [254]:
b = np.array([0, 1, 2], dtype='int32') # 尝试减少位数

In [255]:
b.dtype

dtype('int32')

In [256]:
b

array([0, 1, 2], dtype=int32)

In [257]:
c = np.array([0, 1, 2], dtype='float') # float和int的默认位数是64

In [258]:
c #  与c元素的表示方法为int时不同，数值里会附带小数点

array([0., 1., 2.])

In [259]:
d = np.array([3e50, 4e35], dtype='int64') #  如果位数太大，无法使用'int'表示时会产生溢出错误

OverflowError: Python int too large to convert to C long

In [260]:
d = np.array([3e50, 4e35], dtype='float64') #  如果改成float，就可以成功地生成数组

In [261]:
e = np.array([3.5, 4.2, -4.3], dtype='int') # 即使是使用小数表示的数组，如果数据类型被设置为int，则只有整数部分被保留

In [262]:
e

array([ 3,  4, -4])

In [263]:
f = np.array([0, 3, 0, -1], dtype = 'bool') #将0转换为False，如果不是0，则转换为True

In [264]:
f

array([False,  True, False,  True])

In [265]:
g = np.array([0., 1., 2.], dtype='int64')

In [266]:
g

array([0, 1, 2])

In [267]:
g.dtype = 'int32' # 将数据类型转换为int32

In [268]:
g

array([0, 0, 1, 0, 2, 0], dtype=int32)

In [269]:
g.dtype = 'float64' #将数据类型转换为float64

In [270]:
g

array([0.e+000, 5.e-324, 1.e-323])

In [271]:
g.dtype = 'float32' # 将位数转换为32

In [272]:
g

array([0.e+00, 0.e+00, 1.e-45, 0.e+00, 3.e-45, 0.e+00], dtype=float32)

In [273]:
g.dtype = 'int64' #  将数据类型恢复为原有类型，则数据的值也会恢复

In [274]:
g

array([0, 1, 2])

In [275]:
h = np.random.randint(10, size=100, dtype='int8') # 生成100个0~9的整数。数据类型是'int8'

In [276]:
i = np.random.randint(10, size=100, dtype='int64') #  将位数设置为64

In [277]:
h.nbytes # 确认字节数

100

In [278]:
i.nbytes #  变为h的8倍

800

## 1.8 副本与视图的区别

### 1.8.1 副本和视图

In [279]:
import numpy as np

In [280]:
a = np.array([1, 2, 3])

In [281]:
d = a.view() #创建视图

In [282]:
d

array([1, 2, 3])

In [283]:
d[0] = 100 # 改变视图中的一个值

In [284]:
d

array([100,   2,   3])

In [285]:
a # 原有数组a中的数据也被改变了

array([100,   2,   3])

In [286]:
c = a.copy()

In [287]:
c[1] = 25

In [288]:
c

array([100,  25,   3])

In [289]:
a

array([100,   2,   3])

### 1.8.2 不同操作方式的区别

In [290]:
a = np.array([1, 2, 3])

In [291]:
b = a # 将a代入b中

In [292]:
id(a) == id(b) # 确认引用的内存地址是否相同

True

In [293]:
a = np.array([1, 2, 3])

In [294]:
c = a[:] #  换一种语法

In [295]:
id(a) == id(c) #可以看出引用的是不同的对象

False

In [296]:
c[1] = 22 # 修改c的一部分

In [297]:
a # 对c做的修改也在a中被反映了出来

array([ 1, 22,  3])

In [298]:
d = a[:1]

In [299]:
id(d) == id(a)

False

In [300]:
d[0] = 11

In [302]:
a

array([11, 22,  3])

In [303]:
d

array([11])

In [304]:
c

array([11, 22,  3])

In [305]:
e = a.copy() #代入a的副本

In [306]:
e.base is a

False

In [307]:
e[2] = 234

In [308]:
e

array([ 11,  22, 234])

In [309]:
a

array([11, 22,  3])

In [310]:
print(a.base)

None


In [311]:
f = a.copy()

In [312]:
f.base is a

False

In [313]:
a = np.array([1, 2, 3])

In [314]:
c = a # 创建作为视图的变量c

In [315]:
a = a + 1 #加1

In [316]:
c # 加法运算没有被反映到c中

array([1, 2, 3])

In [317]:
a

array([2, 3, 4])

In [318]:
a = np.array([1, 2, 3])

In [319]:
c = a

In [320]:
a += 1

In [321]:
c

array([2, 3, 4])

In [322]:
a

array([2, 3, 4])

In [323]:
a = np.array([1, 2, 3])

In [324]:
c = a

In [325]:
np.add(a, 1, out=a)

array([2, 3, 4])

In [326]:
a

array([2, 3, 4])

In [327]:
c

array([2, 3, 4])

In [328]:
def test():
    import numpy as np
    import time
    X = np.ones(100000000, dtype='int8')
    Y = np.ones(100000000, dtype='int8')
    a = time.time()
    for _ in range(100):
        X = X*4 + Y*3
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('X = X*4 + Y*3: {} sec'.format((b-a)/100))
    a = time.time()
    for _ in range(100):
        X *= 4
        X += Y*3
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('X *= 4; X += Y*3: {} sec'.format((b-a)/100))
    a = time.time()
    for _ in range(100):
        np.multiply(X, 4, out=X)
        np.multiply(Y, 3, out=Y)
        np.add(X, Y, out=X)
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print("using functions: {} sec".format((b-a)/100))

In [329]:
test()

X = X*4 + Y*3: 0.06491099119186401 sec
X *= 4; X += Y*3: 0.05268529176712036 sec
using functions: 0.039980568885803223 sec


In [330]:
a = np.random.randn(2, 3, 9)

In [331]:
b = a.ravel()

In [332]:
c = a.flatten()

In [333]:
a

array([[[-0.7313391 , -0.58637525,  0.28246838, -0.26983088,
          1.15510886, -0.50769539,  1.45690857,  0.2710993 ,
         -0.57456987],
        [-0.9524522 , -2.12408864,  0.80256299, -0.22294196,
          0.01932229,  0.22030178,  0.39542361,  1.14064577,
         -1.45688255],
        [-2.32868627, -0.31466955,  0.83350398,  1.9762407 ,
         -0.67467305, -0.5555083 ,  0.77332746,  1.06025268,
         -0.11096814]],

       [[ 1.75840375,  0.60398718, -0.85877941,  0.12620501,
          0.16310266,  0.3097929 , -1.35977511, -0.23872914,
          0.09136026],
        [-0.29315379, -0.52892942,  0.30003008,  0.7948672 ,
         -0.86535445,  0.23261189,  0.09787488,  0.07083721,
          1.48370513],
        [-1.13607076,  0.29849953, -0.2648803 , -0.61182212,
         -1.73459688, -0.74316629, -1.42798168,  1.32940988,
          1.34048133]]])

In [334]:
a[0,0,0] = 129

In [336]:
a[0,0,0], b[0], c[0]

(129.0, 129.0, -0.7313390950858908)

In [337]:
a = np.random.randint(10, size=100)

In [338]:
a

array([7, 0, 4, 8, 6, 2, 7, 1, 4, 8, 4, 8, 0, 2, 1, 1, 5, 0, 0, 3, 1, 4,
       1, 0, 1, 4, 8, 9, 9, 8, 5, 9, 9, 5, 8, 0, 5, 3, 1, 9, 4, 9, 3, 7,
       2, 3, 3, 6, 3, 1, 1, 2, 3, 1, 4, 2, 1, 5, 8, 5, 9, 5, 4, 3, 6, 6,
       6, 6, 6, 4, 3, 7, 1, 0, 0, 7, 1, 1, 7, 4, 5, 6, 8, 1, 4, 9, 4, 1,
       3, 6, 4, 9, 4, 0, 1, 3, 3, 5, 7, 6])

In [339]:
n = a%3==0 # 3的倍数的位置上是True

In [340]:
n

array([False,  True, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False,  True,
        True,  True, False, False, False,  True, False, False, False,
        True,  True, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False,  True,  True, False, False,
        True,  True,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False,  True, False,  True, False,  True,  True, False, False,
        True])

In [341]:
a[n] #将3的倍数的元素提取出来

array([0, 6, 0, 0, 0, 3, 0, 9, 9, 9, 9, 0, 3, 9, 9, 3, 3, 3, 6, 3, 3, 9,
       3, 6, 6, 6, 6, 6, 3, 0, 0, 6, 9, 3, 6, 9, 0, 3, 3, 6])

In [342]:
k = a[n]

In [344]:
np.may_share_memory(a, k) #  用于确认内存是否是共享的函数。详细内容将在1.8.5小节中进行讲解

False

In [345]:
f = a[np.arange(0, 10, 2)]

In [346]:
f

array([7, 4, 6, 7, 4])

In [347]:
np.may_share_memory(a, f)

False

In [348]:
a = np.array([1, 2, 3])

In [349]:
b = a

In [350]:
c = b

In [351]:
d = a.copy()

In [352]:
np.may_share_memory(a, b) # 如果是True，则说明b是a的视图

True

In [353]:
np.may_share_memory(a, c) # 这里也返回True

True

In [354]:
np.may_share_memory(a, d) #  由于d是a的副本，因此返回False

False

In [355]:
np.shares_memory(a, b) # 更严谨的判断使用share_memory函数

True

In [356]:
np.shares_memory(a, d)

False