▲示例2.31：NumPy 的导入

In [1]:
import numpy

▲示例2.32：为模块指定其他名称

In [2]:
import numpy as np

▲示例2.33：从 Python 列表中创建 NumPy 数组

In [3]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])  # 从 Python 列表中创建 NumPy 数组
print(a) 

[0 1 2 3 4 5]


▲示例2.34：从双重列表中创建二维的 NumPy 数组

In [4]:
import numpy as np

b = np.array([[0, 1, 2], [3, 4, 5]])  # 从双重列表中创建二维的 NumPy 数组
print(b)

[[0 1 2]
 [3 4 5]]


▲示例2.35：从三重列表中创建三维的 NumPy 数组

In [11]:
import numpy as np

c = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])  # 从三重列表中创建三维的 NumPy 数组
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


▲示例2.36：生成数组的各种函数

In [12]:
import numpy as np

d = np.zeros(8)  # 包含8个0的数组
print(d)

e = np.ones(8)  # 包含8个1的数组
print(e)

f = np.arange(8) # 包含0到7的数组
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


▲示例2.37：用 shape() 函数获取数组的形状

In [13]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2×3 的二维数组
print(np.shape(a))  # 表示a的形状

(2, 3)


▲示例2.38：利用 len() 函数获得最外侧的元素数

In [14]:
print(len(a))  # 获得a的行数

2


▲示例2.39：数组和数值的运算

In [15]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 二维数组

print(a) 
print()
print(a + 3)  # 各元素加3
print()
print(a * 3)  # 各元素乘3

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


▲示例2.40：数组间的运算

In [16]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])  # 二维数组

c = np.array([[2, 0, 1],
              [5, 3, 4]])  # 二维数组

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


▲示例2.41：通过指定索引，访问数组中的元素

In [17]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[3])  # 指定索引

4


▲示例2.42：通过指定索引，交换数组中的元素

In [18]:
a[2] = 9
print(a)

[1 2 9 4 5]


▲示例2.43：访问二维数组中的元素

In [19]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])

print(b[1, 2])  # 与 b[1][2]相同

5


▲示例2.44：交换二维数组中的元素

In [20]:
b[1, 2] = 9

print(b)

[[0 1 2]
 [3 4 9]]


▲示例2.45：访问行或列

In [21]:
c = np.array([[0, 1, 2],
              [3, 4, 5]])

print(c[1, :])  # 检索索引为1的行

print()

c[:, 1] = np.array([6, 7])  # 替换索引为1的列
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


▲示例2.46：作为函数参数以及返回值的数组

In [22]:
import numpy as np

def my_func(x):
    y = x * 2 + 1
    return y

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 二维数组
b = my_func(a)  # 将数组作为参数传递，并作为返回值接收

print(b)

[[ 1  3  5]
 [ 7  9 11]]


▲示例2.47：NumPy 提供的各种函数

In [23]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  #  2维数组

print("统计:", np.sum(a))
print("平均:", np.average(a))
print("最大值:", np.max(a))
print("最小值:", np.min(a))

统计: 15
平均: 2.5
最大值: 5
最小值: 0


#### 问题

　在 Jupyter Notebook 的单元格中编写两个 NumPy 的二维数组，并计算它们的和、差和乘积（示例 2.48）。

#### 解答示例

▲示例2.48：解答示例

In [24]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])
b = np.array([[5, 4, 3],
              [2, 1, 0]])

print(a + b)  # 和
print()
print(a - b)  # 差
print()
print(a * b)  # 积

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
