## 2.2赋值

In [1]:
import scipy.constants as pc

In [2]:
'{0:12.4e}'.format(pc.h)

'  6.6261e-34'

In [3]:
import numpy as np

In [4]:
x = np.array( [112.2, 10.9, 13.6, 8.4, 11.1 ] )

In [5]:
x

array([112.2,  10.9,  13.6,   8.4,  11.1])

In [6]:
A = np.array( [ [ 2, 4 ], [ 1, 3 ] ] )

In [7]:
A

array([[2, 4],
       [1, 3]])

In [8]:
A = np.matrix(' 2 4 ; 1 3 ')

In [9]:
A

matrix([[2, 4],
        [1, 3]])

In [10]:
x = np.matrix( ' 12.2 10.9 13.6 8.4 11.1 ' )

In [11]:
x

matrix([[12.2, 10.9, 13.6,  8.4, 11.1]])

In [12]:
w = np.matrix( ' 12.2 ; 10.9 ; 13.6 ; 8.4 ; 11.1 ' )

In [13]:
w

matrix([[12.2],
        [10.9],
        [13.6],
        [ 8.4],
        [11.1]])

In [14]:
w[2, 0]

13.6

In [15]:
A[0, 1]

4

In [16]:
Z = np.zeros([5, 3])

In [17]:
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
Zm = np.matrix(Z)

In [19]:
Zm

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
O = np.ones((2,3))

In [21]:
O

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
I = np.eye(3,3)

In [26]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
A[0,:]

matrix([[2, 4]])

In [28]:
A[:,1]

matrix([[4],
        [3]])

In [29]:
x[0, 0:2]

matrix([[12.2, 10.9]])

In [30]:
x = np.arange(0,1,0.1)

In [31]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [33]:
d = np.linspace(1,100,8)

In [34]:
d

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

In [35]:
np.logspace(-1,2,4)

array([1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [36]:
np.logspace(1,6,6,base=2.0)

array([ 2.,  4.,  8., 16., 32., 64.])

## 2.3数学运算